apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oaga5n99u-go
  janus-idp.io/tekton: oaga5n99u-go
  backstage.io/kubernetes-id: oaga5n99u-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oaga5n99u-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
